### ISSUE TITLE
Cassandra Service - save fails for large documents

### ISSUE THREAD

**Issue by rsoika** [imixs/imixs-archive#57]
If a single attachment is about 20MB than the save method failed with the following exception

```
10:59:09,318 INFO  [org.imixs.archive.service.MessageService] (EJB default - 1) Scheduler failed (last uniqueid=1521705cd66-1dd38c33-1552762401163) : Cassandra failure during write query at consistency LOCAL_ONE (1 responses were required but only 0 replica responded, 1 failed),
	at java.lang.Thread.run(Thread.java:748),
	at org.jboss.threads.JBossThread.run(JBossThread.java:485),
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624),
10:59:09,324 INFO  [org.imixs.archive.service.MessageService] (EJB default - 1) Failed to stop timer - java.lang.IllegalMonitorStateException,
10:59:09,324 INFO  [org.imixs.archive.service.MessageService] (EJB default - 1) Timer stopped. ,
10:59:11,562 ERROR [org.jboss.as.ejb3.timer] (EJB default - 1) WFLYEJB0020: Error invoking timeout for timer: [id=d4c6c9c2-5c30-4479-8f8e-b4c870197b3f timedObjectId=imixs-archive-service-1.2.4-SNAPSHOT.imixs-archive-service-1.2.4-SNAPSHOT.SyncService auto-timer?:false persistent?:true timerService=org.jboss.as.ejb3.timerservice.TimerServiceImpl@270efd0e initialExpiration=null intervalDuration(in milli sec)=0 nextExpiration=Tue Apr 30 11:00:00 CEST 2019 timerState=CANCELED info=IMIXS_ARCHIVE_SYNC_TIMER]: org.jboss.as.ejb3.tx.TimerTransactionRolledBackException: WFLYEJB0110: Timer invocation failed, transaction rolled back
```

**Comment by rsoika** [comment]
We need to implement a DocumentSplitter 

See: https://ralph.blog.imixs.com/2018/06/29/cassandra-how-to-handle-large-media-files/
